# Generated by Django 3.2.4 on 2021-06-09 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b019cdbd-0a80-4cf0-9639-44ee7cf5d457'), editable=False, primary_key=True, serialize=False),
        ),
    ]
